apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  labels:
    spring-cloud-service: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    name: rabbitmq
