apiVersion: v1
kind: ReplicationController
metadata:
  name: skipper
spec:
  replicas: 1
  selector:
    name: skipper
  template:
    metadata:
      labels:
        name: skipper
    spec:
      containers:
      - name: skipper
        image: springcloud/spring-cloud-skipper-server
        imagePullPolicy: Always
        ports:
        - containerPort: 7577
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: SERVER_PORT
          value: '7577'
        - name: SPRING_CLOUD_SKIPPER_SERVER_URI
          value: 'http://${SKIPPER_SERVER_URI}:${SKIPPER_SERVICE_PORT}'
          # Add Maven repo for metadata artifact resolution
        - name: SPRING_APPLICATION_JSON
          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"https://repo.spring.io/libs-snapshot\"} } } }"

---

kind: Service
apiVersion: v1
metadata:
  name: skipper
  labels:
    spring-cloud-service: skipper
spec:
  # If you are running k8s on a local dev box, you can use type NodePort instead
  type: LoadBalancer
  ports:
    - port: 7577
  selector:
    name: skipper
